services:
  - type: web
    name: mindponto-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: RH_IDS
        sync: false
      - key: WORKER_URL
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true 